---
title: "COVID-19 Forecasting Model Metadata"
author: "Nutcha Wattanachit and Li Shandross"
date: "06/06/2021"
header-includes:
   - \usepackage{tabularx}
   - \usepackage{hyperref}
   - \usepackage{wrapfig}
   - \usepackage{float}
   - \usepackage{colortbl}
   - \usepackage{pdflscape}
   - \usepackage{tabu}
   - \usepackage{xcolor}
output:
  pdf_document:
        latex_engine: xelatex
---

```{r setup, include=FALSE}
library(tidyverse)
library(energy)
library(knitr)
library(data.table)
library(covidHubUtils)
#devtools::install_github("reichlab/covidHubUtils")
library(lubridate)
library(zoltr)
library(igraph)
library(gtools)
library(gridExtra)
knitr::opts_chunk$set(echo=FALSE,
                       comment = FALSE, message=FALSE, fig.show= 'hold',fig.pos="H",table.placement='H',
                       fig.align = 'center')
```


# COVID-19 Death Count Forecasting Models' Metadata

```{r}
source("./functions/metadata_functions.R")
source("./functions/distance_func_script.R")

# set targets for analysis
target_horizon <- 1:4
target_var <- c("inc death","inc case")
#load in data to get models
wide_frame_death <- read.csv("./data/quantile_frame.csv") 
d_frame <- frame_format(wide_frame_death) 
# extract models
death_model_list <- colnames(d_frame)[7:ncol(d_frame)]
rm(wide_frame_death,d_frame)

## start pulling
metadata_list <- sapply(death_model_list,
                        function(x)
                        list.files("./data/metadata")[grepl(x,list.files("./data/metadata"))])
# set colnames
col_info <- c("team_name", 
                                 "model_name", 
                                 "model_abbr", 
                                 "model_contributors", 
                                 "website_url", 
                                 "license", 
                                 "team_model_designation", 
                                 "methods",
                                 "institutional_affil",
                                 "team_funding",
                                 "repo_url",
                                 "twitter_handles",
                                 "data_inputs",
                                 "citation",
                                 "methods_long")
# start processing

check <- get_metadata_table(paste0("./data/metadata/",metadata_list[1]),
                            sep = ": ",
                            fill = TRUE, 
                            header = FALSE)

check <- read.table(paste0("./data/metadata/",metadata_list[2]),
                    sep = ":",
                    quote="",
                    fill = TRUE, 
                    header = FALSE)

check2 <- read.table(paste0("./data/metadata/",metadata_list[1]),
                    sep = ":",
                    quote="",
                    fill = TRUE, 
                    header = FALSE)

get_metadata_full <- map_dfr(metadata_list, 
                             function(metadata_list) {
                               get_metadata_table(paste("./data-processed/", metadata_list, sep = ""), 
                                                  sep = ":", 
                                                  fill = TRUE, 
                                                  header = FALSE) 
                             })

## for some reason, this doesn't work using the full list
metadata_list_full <- list.files(path = "./data-processed", pattern = "metadata", 
                                 recursive = TRUE, ignore.case = FALSE, include.dirs = TRUE)

get_metadata_full2 <- map_dfr(metadata_list_full, 
                             function(metadata_list_full) {
                               get_metadata_table(paste("./data-processed/", metadata_list_full, sep = ""), 
                                                  sep = ":", 
                                                  fill = TRUE, 
                                                  header = FALSE) 
                             })

#add col names
colnames(get_metadata_full) <- c("team_name", 
                                 "model_name", 
                                 "model_abbr", 
                                 "model_contributors", 
                                 "website_url", 
                                 "license", 
                                 "team_model_designation", 
                                 "methods",
                                 "institutional_affil",
                                 "team_funding",
                                 "repo_url",
                                 "twitter_handles",
                                 "data_inputs",
                                 "citation",
                                 "methods_long")
```



# COVID-19 Case Count Forecasting Models' Metadata

```{r}
#load in data to get models
wide_frame_case <- read.csv("./data/quantile_frame_inc.csv") 
c_frame <- frame_format(wide_frame_case,c_frame) 
# extract models
case_model_list <- colnames(c_frame)[7:ncol(c_frame)]
rm(wide_frame_case)
```

